### ISSUE TITLE
Mongoid model named Channel is overriden by Channel module

### ISSUE THREAD

**Issue by kinnrot** [Microsoft/ApplicationInsights-Ruby#20]
For some reason, once requiring this gem, I get the following error message when server boots
> WARN -- : Channel is not a class

Channel is defined for me as a model in the models folder.

for some reason module from this gem overrides my class definition.

**Comment by satoryu** [comment]
Could you give us full of stacktrace you faced, version of application_insight ?

**Comment by SergeyKanzhelev** [comment]
Closing as there is no repro. And just looking at code - `Channel` is already inside `AplicationInsights` module. Please re-open if this is still an issue
