### ISSUE TITLE
Format of the request duration TimeSpan in Rack middleware is incorrect

### ISSUE THREAD

**Issue by juliushardt** [Microsoft/ApplicationInsights-Ruby#21]
Recently, [a typo in the description of the RequestData duration string](https://github.com/Microsoft/ApplicationInsights-Home/issues/115) has been [fixed](https://github.com/Microsoft/ApplicationInsights-Home/commit/804a33e3e9abef9d01cfeca102f459e0b4edaed1) in the Application Insights API. Unfortunately, the Rack 'TrackRequest' middleware sends incorrectly formatted requests, because the `format_request_duration` method still uses the incorrect format `d:hh:mm:ss.fffffff`, whereas it should be `d.h:mm:ss.fffffff` (the 'days' portion of the duration string [needs to be separated with a dot, not a colon](https://social.msdn.microsoft.com/Forums/vstudio/en-US/1c626c8e-0f6a-49a3-9b3c-7fd77fe8d108/field-duration-on-type-requestdata-is-not-a-valid-duration-string-even-though-it-is-valid?forum=ApplicationInsights)).

Related pull request: #19

**Comment by satoryu** [comment]
@AaronPatterson @dnduffy this issue looks able to be closed.
