### ISSUE TITLE
Release 0.5.4

### ISSUE THREAD

**Issue by satoryu** [Microsoft/ApplicationInsights-Ruby#33]
It's been about 2 months since PR #31 was merged. But this latest version has not been released 😭 

Please do it!

https://rubygems.org/gems/application_insights

**Comment by satoryu** [comment]
ping @AaronPatterson @dnduffy

**Comment by satoryu** [comment]
It's been 4 months since I pinged...

**Comment by SergeyKanzhelev** [comment]
@yantang-msft do you OK ship what we have now as 0.5.4 and than ship your changes later? Any objections?

**Comment by yantang-msft** [comment]
@SergeyKanzhelev NP, as long as you don't mind doing another release.

**Comment by SergeyKanzhelev** [comment]
Released and tagged: https://github.com/Microsoft/ApplicationInsights-Ruby/blob/v0.5.4/CONTRIBUTING.md
