### ISSUE TITLE
Update schema to the latest version

### ISSUE THREAD

**Issue by yantang-msft** [Microsoft/ApplicationInsights-Ruby#52]
The schema is very old, the RemoteDependencyData for example.

Here is a good start point: https://github.com/Microsoft/ApplicationInsights-Ruby/tree/sergkanz/schemaUpdate. But it need more work as it breaks the build.

**Comment by yantang-msft** [comment]
There are two bugs in the schema generator.
1) If there is no attribute of the class, then json_serializeable will complain expecting 1 argument but receive 0. This happens for domain.rb. A simple fix is to give an default parameter empty hash to the json_serializable.
2) The generated schema for page_view_perf_data.rb is simply incorrect. Need further investigation for this bug.

Other than that, there is some test failures as well. But should be easier to fix.

**Comment by SergeyKanzhelev** [comment]
@yantang-msft you should have access to generator. Would you have time to look into it?

**Comment by yantang-msft** [comment]
@SergeyKanzhelev Yes, I already fixed couple bugs of the generator, working on fixing test cases now.

**Comment by yantang-msft** [comment]
Completed in https://github.com/Microsoft/ApplicationInsights-Ruby/pull/57
